blank_issues_enabled: false

contact_links:
  - name: 🌐 The Alchemist's Ledger
    url: https://7mxdie.github.io/gts-alchemy/
    about: Open the website.

  - name: 💬 Gate to Sovngarde Discord
    url: https://discord.gg/gatetosovngarde
    about: Discuss the project with the community.